server:
  port: 8012

oss:
  enable: true
  name: minio
  tenant-mode: true
  endpoint: http://10.93.1.43:9000
  access-key: ADMIN
  secret-key: PASSWORD
  bucket-name: bladex
#数据源配置
spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}
