server:
  port: 8012

oss:
  enable: true
  name: minio
  #是否开启租户模式，true：桶名称默认使用租户id+桶名称（000000-bladex） false:取桶名称
  tenant-mode: false
  endpoint: http://10.93.1.43:9000
  access-key: ADMIN
  secret-key: PASSWORD
  bucket-name: bladex
#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

