#服务器端口
server:
  port: 8107

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
api:
  file:
    ftlPath: D:/ftl/

logging:
  config: classpath:logback.xml

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:7019/xxl-job-admin
    executor:
      appname: blade-contract
      ip: 127.0.0.1
      logpath: ../data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 7018
