#服务器端口
server:
  port: 8107

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
api:
  file:
    ftlPath: D:/ftl/
  eSeal:
    tokenUrl: http://sa.pec.com.cn:9080/common/user/access
    tokenSY: http://sa.pec.com.cn:9080/common/file/addWatermark
    tokenXZ: http://sa.pec.com.cn:9080/common/file/downloadWaterMarkDoc/
    username: admin_ekp
    password: c5c85e7ef7747ce3f1649f44feb8b3bf

logging:
  config: classpath:logback.xml

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://localhost:7019/xxl-job-admin
    executor:
      appname: blade-contract
      ip: 127.0.0.1
      logpath: ../data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 7018
