#服务器端口
server:
  port: 8107

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.prod.url}
    username: ${blade.datasource.prod.username}
    password: ${blade.datasource.prod.password}
api:
  file:
    ftlPath: /ftl/
  eSeal:
    tokenUrl: https://unici.pec.com.cn/common/user/access
    tokenSY: https://unici.pec.com.cn/common/file/addWatermark
    tokenXZ: https://unici.pec.com.cn/common/file/downloadWaterMarkDoc/
  signing:
    day: 15
logging:
  config: classpath:logback.xml
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://localhost:7019/xxl-job-admin
    executor:
      appname: blade-contract
      ip: 127.0.0.1
      logpath: ../data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 7018
