#服务器端口
server:
  port: 8107

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}
api:
  file:
    ftlPath: /ftl/


logging:
  config: classpath:logback.xml

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://10.93.1.43:7019/xxl-job-admin
    executor:
      appname: blade-contract
      ip: 10.93.1.43
      logpath: ../data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 7018
