#数据源配置
spring:
  datasource:
    # MySql
    url: jdbc:mysql://39.98.158.74:3306/bladex_flow?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: barcode
    # PostgreSQL
    #url: jdbc:postgresql://127.0.0.1:5432/bladex_flow
    #username: postgres
    #password: 123456
    # Oracle
    #url: jdbc:oracle:thin:@127.0.0.1:49161:orcl
    #username: BLADEX_FLOW
    #password: oracle
