#服务器端口
server:
  port: 9008

#flowable配置 （\u5B8B\u4F53 - 宋体）
flowable:
  activity-font-name: \u5B8B\u4F53
  label-font-name: \u5B8B\u4F53
  annotation-font-name: \u5B8B\u4F53
  check-process-definitions: false
