#spring配置
spring:
  redis:
    ##redis 单机环境配置
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: oracle.jdbc.OracleDriver
    druid:
      # MySql、PostgreSQL校验
      validation-query: select 1
      # Oracle校验
      #validation-query: select 1 from dual

#项目模块集中配置
blade:
  #分布式锁配置
  lock:
    enabled: false
    address: redis://127.0.0.1:6379
  #通用开发生产环境数据库地址(特殊情况可在对应的子工程里配置覆盖)
  datasource:
    dev:
      # MySql
      url: jdbc:mysql://localhost:3306/bladex?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: root
      # PostgreSQL
      #url: jdbc:postgresql://127.0.0.1:5432/bladex
      #username: postgres
      #password: 123456
      # Oracle
      #url: jdbc:oracle:thin:@127.0.0.1:49161:orcl
      #username: BLADEX
      #password: oracle
  document:
    resources:
      - name: 授权模块
        location: /blade-auth
      - name: 工作台模块
        location: /blade-desk
      - name: 系统模块
        location: /blade-system
