#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}

api:
  ssoUrl: http://upht.pec.com.cn
  serviceURL: http://upht.pec.com.cn/api/blade-auth/auth/login
  tokenUrl: http://upht.pec.com.cn/api/blade-auth/oauth/token
