#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.prod.url}
    username: ${blade.datasource.prod.username}
    password: ${blade.datasource.prod.password}
api:
  ssoUrl: http://cms.pec.com.cn
  serviceURL: http://cms.pec.com.cn/api/blade-auth/auth/login
  tokenUrl: https://cms.pec.com.cn/api/blade-auth/oauth/token
