#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
api:
  ssoUrl: http://localhost:1888
  serviceURL: http://localhost:8080/api/blade-auth/auth/login
  tokenUrl: http://localhost:8080/api/blade-auth/oauth/token
