server:
  port: 18080
spring:
  aop:
    auto: true
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
api:
  doc:
    tokenUrl: http://oatest-interface.pec.com.cn/common/pursuant/token
    docInfoUrl: http://oatest-interface.pec.com.cn/common/pursuant/docs
    #相对方资料接口
    counterpartUrl: http://oatest-interface.pec.com.cn/common/opposite/data
    SecurityKey: zwtwyx3f1kj5x3nlcnjzpy2u
    username: dev_c_p
    password: oa0/YNY374PKB53+IUmjiw==
  ekp:
    tokenUrl: http://oatest.pec.com.cn:9080/restful/ekp/getToken
    ekpUrl: http://oatest.pec.com.cn:9080/restful/ekp/genhrbill
    account: iHR
    password: oaekp
    fdTemplateId: 176212613bf6f84e6bf1ad942cbb8344
    ftlPath: D:/ftl/
  organization_cs:
    wsdl: http://oatest.pec.com.cn:8080/sys/webservice/organizationWebService?wsdl
    namespace: http://sys.webservice.client
    method: updateOrganization
    account: shebake_test
    password: d65937df2000cc755253956bd1403aa5
  organization:
    wsdl: https://oa.pec.com.cn/sys/webservice/organizationWebService?wsdl
    namespace: http://sys.webservice.client
    method: updateOrganization
    account: shebake
    password: 80372a095c16319ce09ef7cc2c871b53
  eSeal:
    tokenUrl: http://sa.pec.com.cn:9080/common/user/access
    orgInfoByCodeUrl: http://sa.pec.com.cn:9080/common/apply/company/getByOrganCode
    orgInfoBySysUidUrl: http://sa.pec.com.cn:9080/common/apply/company/getBySysUid
    uploadFileDivideUrl: http://sa.pec.com.cn:9080/common/file/upload/divide
    uploadFileMergeUrl: http://sa.pec.com.cn:9080/common/file/upload/merge
    viewUrl: http://sa.pec.com.cn:9080/common/file/contract/view
    downloadUrl: http://sa.pec.com.cn:9080/common/file/downloadSinged
    singleSignUrl: http://sa.pec.com.cn:9080/common/run/esign/singleSign
    sendSmsUrl: http://sa.pec.com.cn:9080/common/run/esign/sendSms
    multiSignUrl: http://sa.pec.com.cn:9080/common/run/esign/multiSign
    username: 1111
    password: 1111

