server:
  port: 18080
spring:
  aop:
    auto: true
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}
api:
  doc:
    tokenUrl: https://oatest-interface.pec.com.cn/common/pursuant/token
    docInfoUrl: https://oatest-interface.pec.com.cn/common/pursuant/docs
    #相对方资料接口
    counterpartUrl: https://oatest-interface.pec.com.cn/common/opposite/data
    SecurityKey: zwtwyx3f1kj5x3nlcnjzpy2u
    username: dev_c_p
    password: oa0/YNY374PKB53+IUmjiw==
  ekp:
    tokenUrl: https://oatest-interface.pec.com.cn/restful/ekp/getToken
    ekpUrl: https://oatest-interface.pec.com.cn/restful/ekp/genhrbillouts
    account: iHR
    password: oaekp
    fdTemplateId: 176212613bf6f84e6bf1ad942cbb8344
    ftlPath: /ftl/
  organization:
    wsdl: https://oatest.pec.com.cn/sys/webservice/organizationWebService?wsdl
    namespace: https://sys.webservice.client
    method: updateOrganization
    account: shebake_test
    password: d65937df2000cc755253956bd1403aa5
  eSeal:
    tokenUrl: https://sa.pec.com.cn:9080/common/user/access
    tokenSY: https://sa.pec.com.cn:9080/common/file/addWatermark
    tokenXZ: https://sa.pec.com.cn:9080/common/file/downloadWaterMarkDoc/
    orgInfoByCodeUrl: https://sa.pec.com.cn:9080/common/apply/company/getByOrganCode
    orgInfoBySysUidUrl: https://sa.pec.com.cn:9080/common/apply/company/getBySysUid
    uploadFileDivideUrl: https://sa.pec.com.cn:9080/common/file/upload/divide
    uploadFileMergeUrl: https://sa.pec.com.cn:9080/common/file/upload/merge
    viewUrl: https://sa.pec.com.cn:9080/common/file/contract/view
    downloadUrl: https://sa.pec.com.cn:9080/common/file/downloadSinged
    singleSignUrl: https://sa.pec.com.cn:9080/common/run/esign/singleSign
    sendSmsUrl: https://sa.pec.com.cn:9080/common/run/esign/sendSms
    multiSignUrl: https://sa.pec.com.cn:9080/common/run/esign/multiSign
    username: 1111
    password: 1111

